#! /bin/sh
if command -v cabal > /dev/null; then
  if ! command -v ghc-prof-flamegraph > /dev/null; then
    echo -e 'ghc-prof-flamegraph was not found on your PATH, installing now\n'
    cabal install ghc-prof-flamegraph
  fi
else
  echo 'This script requires cabal'
  echo 'Please install the haskell-platform'
  return 1
fi

# TODO: https://www.fpcomplete.com/blog/2015/04/ghc-prof-flamegraph
