#! /bin/bash

# Add the script folder to the path
export BASH_DIR="${HOME}/.config/bash"
export PATH="${PATH}:${BASH_DIR}/scripts"

# TERM settings
if [ -z ${TMUX+x} ]; then
  export TERM=xterm-256color
else
  export TERM=screen-256color
fi

# svn settings #
export SVN_EDITOR=vi

## History Options
## ==============

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000


## Bash Options
## ===========

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# Make less output colors
export LESS='-R'

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    . /etc/bash_completion

# Mac Bash Completions
elif command -v brew > /dev/null; then
  if [ -f `brew --prefix`/etc/bash_completion ]; then
    . `brew --prefix`/etc/bash_completion
  fi
fi

# Activate Powerline bindings
export POWERLINE_CONFIG_COMMAND="${HOME}/.vim/bundle/powerline/powerline/bindings/bash/powerline.sh"
if ! ps -e | grep 'powerline-daemon -q' | grep -v 'grep' > /dev/null; then
  echo 'powerline daemon'
  powerline-daemon -q
  . POWERLINE_CONFIG_COMMAND
fi
