#! /bin/sh
git config --global core.editor vim

git config --global color.diff always
git config --global color.grep always
git config --global color.status always
git config --global color.ui always

if command -v vimdiff > /dev/null; then
  git config --global diff.editor vimdiff
  git config --global merge.tool diffconflicts
  git config --global mergetool.diffconflicts.cmd 'diffconflicts vim $BASE $LOCAL $REMOTE $MERGED'
  git config --global mergetool.diffconflicts.trustExitCode true
  git config --global mergetool.diffconflicts.keepBackup false
fi

git config --global diff.prompt never

exit 0
