" `<sfile>` gives the location of the current file being sourced
" `:p` gives full path rather than relative
" `:h` knocks off the last item in the path
"let $VIMHOME=expand('<sfile>:p:h')
if !exists(':PluginInstall')
  let $VIMHOME=expand('~')

  if !isdirectory(expand("~/.vim/bundle/Vundle.vim/.git"))
    !git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim
  endif

  if !isdirectory(expand("~/.vim/bundle/Vundle.vim/vim-sublime"))
    !git clone https://github.com/grigio/vim-sublime.git ~/.vim/bundle/Vundle.vim/vim-sublime
  endif

  source $VIMHOME/.vim/vundle

  colorscheme Monokai
else
  !echo 'Warning this version of Vim does not support plugins'
  !echo 'Please run sudo apt-get update && sudo apt-get install vim'
  !echo 'To install vim plugins'
endif

if has('syntax') && !exists('g:syntax_on')
  syntax enable
endif

source $VIMHOME/.vim/vim-keymap

" Text editing
set autoindent
set backspace=indent,eol,start
set complete-=i
set listchars=tab:▒░,trail:▓
set list

" Tabs
set tabstop=2 shiftwidth=2 expandtab
set smarttab
set shiftround

" Line numbers
set number

" Show matching bracket
set showmatch

" Show what mode vim is in
set showmode

" Searching
set smarttab
set incsearch
set ic " case insensitive search
set hlsearch

set autoread

" Bottom bar
set laststatus=2
set ruler
set showcmd
set wildmenu

" Numbers
" Allows for Ctrl+a to inrement letters and hex
" Ctrl+x decrements
set nrformats-=alpha,hex

" File handling
set nobackup
set nowritebackup
set noswapfile
set fileformats=unix,dos,mac

" vim-airline
let g:airline#extensions#tabline#enabled = 1
let g:airline_powerline_fonts = 1
let g:airline_theme = 'badwolf'
