# configurations added by github.com/Jiggins/dotfiles

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

## Sourcing files
source ${HOME}/.config/bash/aliases
source ${HOME}/.config/bash/bashOptions
source ${HOME}/.config/bash/prompt

complete -C aws_completer aws