" Vim configurations added by github.com/Jiggins/Bash-Config
let $VIMHOME=expand('<sfile>:p:h').'/.vim'
source $VIMHOME/vundle.vim
source $VIMHOME/vim-commands.vim
source $VIMHOME/vim-keymap.vim
source $VIMHOME/vim-preferences.vim
