" configurations added by github.com/Jiggins/dotfiles
let $VIMHOME=expand('<sfile>:p:h').'/.vim'

if has('mac')
  source $VIMHOME/macos.vim
elseif has('linux')
  source $VIMHOME/linux.vim
endif

source $VIMHOME/vundle.vim
source $VIMHOME/vim-commands.vim
source $VIMHOME/vim-keymap.vim
source $VIMHOME/vim-preferences.vim
